In [1]:
import pandas as pd

In [3]:
TAXI_OWNER_PATH = "/home/gustavo/repos/pandas_specialization/05_joining_data/data/taxi_owners.csv"
TAXI_VEHICLES_PATH = "/home/gustavo/repos/pandas_specialization/05_joining_data/data/taxi_vehicles.csv"

taxi_own = pd.read_csv(TAXI_OWNER_PATH)
taxi_veh = pd.read_csv(TAXI_VEHICLES_PATH)

In [5]:
taxi_own.head(3)

   Unnamed: 0    rid   vid           owner                 address    zip
0           0  T6285  6285  AGEAN TAXI LLC     4536 N. ELSTON AVE.  60630
1           1  T4862  4862    MANGIB CORP.  5717 N. WASHTENAW AVE.  60659
2           2  T1495  1495   FUNRIDE, INC.     3351 W. ADDISON ST.  60618

In [6]:
taxi_veh.head(3)

   Unnamed: 0   vid    make   model  year fuel_type           owner
0           0  2767  TOYOTA   CAMRY  2013    HYBRID  SEYED M. BADRI
1           1  1411  TOYOTA    RAV4  2017    HYBRID     DESZY CORP.
2           2  6500  NISSAN  SENTRA  2019  GASOLINE  AGAPH CAB CORP

### Merging the two tables (inner joint)
inner joins only return the rows with matching values in both tables.

In [15]:
merged = taxi_own.merge(taxi_veh, on="vid", suffixes=("_left", "_rigth"))

In [16]:
merged.head(3)

,Unnamed: 0_left,rid,vid,owner_left,address,zip,Unnamed: 0_rigth,make,model,year,fuel_type,owner_rigth
0,0,T6285,6285,AGEAN TAXI LLC,4536 N. ELSTON AVE.,60630,3057,NISSAN,ALTIMA,2011,HYBRID,AGEAN TAXI LLC
1,1,T4862,4862,MANGIB CORP.,5717 N. WASHTENAW AVE.,60659,644,HONDA,CRV,2014,GASOLINE,MANGIB CORP.
2,2,T1495,1495,"FUNRIDE, INC.",3351 W. ADDISON ST.,60618,2007,TOYOTA,SIENNA,2015,GASOLINE,"FUNRIDE, INC."